name: Deploy Client

on:
  workflow_run:
    workflows: ["Build Client"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: 49cb17e3-8def-43af-825e-dd34bbed57a0
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Redeploy on Railway
        run: railway redeploy --service=${{ env.SVC_ID }} --yes
